### PR TITLE
Use new CanvasKit URL

### LINKED ISSUE #2487: Failing to load canvaskit.js on beta / master
The beta and master channels are requesting `https://dartpad.dev/scripts/canvaskit/canvaskit.js` but this request returns a 404.

### PR DESCRIPTION
**Pull request by johnpryan**
Flutter 3.10 doesn't use `unpkg.com` to load CanvasKit anymore, so this sets the base URL to load CanvasKit from.

See also:
https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/configuration.dart

fixes #2487

This should be deployed at the same time as https://github.com/dart-lang/dart-services/pull/1057

cc: @kevmoo @hterkelsen

### CODE REVIEW

File: lib/sharing/editor_ui.dart [hunk 1]
```diff
@@ -211,18 +216,16 @@ abstract class EditorUi {
...
+            context.htmlSource, context.cssSource, response.result,
+            modulesBaseUrl: response.modulesBaseUrl,
+            addRequireJs: true,
+            addFirebaseJs: shouldAddFirebaseJs,
+            // TODO(srawlins): Determine if we need to destroy the frame when
+            // changing channels.
+            // TODO(ryjohn) Determine how to preserve the iframe
+            // https://github.com/dart-lang/dart-pad/issues/2269
+            destroyFrame: true,
+            canvasKitBaseUrl: _createCanvasKitBaseUrl(version.engineVersion));
```
Comment (parlough) [inline lib/sharing/editor_ui.dart:228]: Won't this break stable since its engine versions don't have `canvaskit.js` stored under their hash yet?

**Review by domesticmouse — APPROVED** [review]

File: lib/sharing/editor_ui.dart (hunk 1 above)
Comment (kevmoo) [reply lib/sharing/editor_ui.dart:228]: Could we add a `legacy` flag here – and just load it from the "old" URL?

Comment (johnpryan) [reply lib/sharing/editor_ui.dart:230]: Good catch, fixed in [b1f3d1a](https://github.com/dart-lang/dart-pad/pull/2490/commits/b1f3d1ae3b3c8669ad48c0107704847f8fc2b8d0)

File: web/scripts/frame.js [hunk 2]
```diff
@@ -83,10 +83,15 @@ messageHandler = function (e) {
...
         // https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/configuration.dart
-        if (obj.canvasKitBaseUrl) {
+        if (obj.canvasKitBaseUrl && !obj.useLegacyCanvasKit) {
             window.flutterConfiguration = {
                 canvasKitBaseUrl: obj.canvasKitBaseUrl
             };
+        } else {
+            // Use legacy CanvasKit URL
+            window.flutterConfiguration = {
+                canvasKitBaseUrl: "https://unpkg.com/canvaskit-wasm@0.37.1/bin/"
```
Comment (kevmoo) [inline web/scripts/frame.js:93]: But we still support Flutter 3.3, right?
Not sure it'll work with this old one...

Comment (johnpryan) [reply web/scripts/frame.js:93]: Yeah the old channel is technically using an incompatible version. It's working for me at least...

Comment (kevmoo) [reply web/scripts/frame.js:93]: then we're fine!

Comment (johnpryan) [reply web/scripts/frame.js:93]: The stable channel will be the old channel soon
