### PR TITLE
fix embeds scrolling / jumping when printing output

### LINKED ISSUE #1301: Embed: page jumps when printing console output
I clicked the run button on Dart embed. The page jumped when it printed the console output.

Kapture 2019-10-01 at 12 55 09

I have this problem on 
- https://dart.dev/codelabs/async-await#example-execution-within-async-functions
- https://dart.dev/#try-dart

I have no problem with the flutter codelab.

Browser: Chrome, Version 77.0.3865.90 (Official Build) (64-bit)
Laptop: Macbook pro

### PR DESCRIPTION
**Pull request by johnpryan**
set console scrollTop instead of using scrollIntoView

closes #1301

### CODE REVIEW

File: lib/experimental/console.dart [hunk 1]
```diff
@@ -42,7 +42,10 @@ class Console {
     if (_bufferedOutput.length == 1) {
       Timer(bufferDuration, () {
         element.element.children.addAll(_bufferedOutput);
-        element.element.children.last.scrollIntoView(ScrollAlignment.BOTTOM);
+        // Using scrollIntoView(ScrollAlignment.BOTTOM) causes the parent page
+        // to scroll, so set the scrollTop instead.
+        var last = element.element.children.last;
```
Comment (RedBrogdon) [inline lib/experimental/console.dart]: nit: final?

**Comment by johnpryan** [comment]
Yes, this works on Firefox and Safari. It looks like http://localhost:8000/experimental/new_embeddings_demo.html has trouble loading in Safari, so I've filed an issue for that https://github.com/dart-lang/dart-pad/issues/1322
