### PR TITLE
iframe dragging bug

### LINKED ISSUE #311: Resizing the code editor area width is tedious when the code contains long strings
See https://dartpad.dartlang.org/a5170ff293b861b3db6b
Resize the editor to about 5cm (so that the url is wrapped several times) and then try to make it wide again.
I either have to move the mouse very slowly or dragging stops after a few millimeters.

### PR DESCRIPTION
**Pull request by kasperpeulen**
fix #311

### CODE REVIEW

File: lib/elements/elements.dart [hunk 1]
```diff
@@ -125,6 +125,7 @@ class DSplitter extends DElement {
       _offset = e.offset;
 
       _moveSub = document.onMouseMove.listen((e) {
+        querySelector("#frame").style.pointerEvents = "none";
```
Comment (devoncarew) [inline lib/elements/elements.dart]: Right now this library doesn't know anything specific about the application that is using it. What if we added two optional params into the ctor of this class, something like `onDragStart` and `onDragEnd`. If non-null, these would be called by the splitter when dragging started and finished. This would allow a consumer of the splitter to enable and disable pointer events on the iframe, without the splitter itself having to know about the iframe.

**Comment by devoncarew** [comment]
lgtm, thanks!
