### PR TITLE
Show confirmation dialog when solution tab is selected

### LINKED ISSUE #1159: Make exercise's solution code more discoverable
Previously we added a solution link to hint flash messages as a short-term fix (https://github.com/dart-lang/dart-pad/issues/1023). From a recent study, we would like to make the solution more discoverable but not giving answers away too easy.

### Proposal 01: Always-visible tab with an extra mask
Users see a alway-visible solution tab from the start. When they click on the solution tab, they would see a mask covering the actual code and suggesting them to check out hints. Users can click on “Show solution” to reveal the solution code.

The initial mockup below demonstrates this proposal. We would optimize visual design and copywriting during the implementation.
image

### Proposal 02: A Solution link in custom error messages

In custom error messages, users will see a link that can open the solution tab. We consider showing this message only when users are stuck (e.g. showing it at the 2nd failed attempt)
image

### PR DESCRIPTION
**Pull request by johnpryan**
fixes #1159

### CODE REVIEW

**Comment by galeyang** [comment]
@johnpryan Could you add a screenshot for this? Thank you!

**Comment by johnpryan** [comment]
Sure, right now it's using a popup from the material design package:  

Screen Shot 2019-07-22 at 10 03 33 AM

**Comment by kwalrath** [comment]
I think it could be clearer, and the Yes/No buttons are confusing. Maybe:

-------------
**Are you sure you want to see the solution?**

If you just want a hint, click **Cancel** and then **Hint**.

[Cancel] [Show the solution]
-------------

**Comment by galeyang** [comment]
I like @kwalrath 's suggestion! I further checked the [Material guideline](https://material.io/design/components/dialogs.html#anatomy)
- Title should contain a brief, clear question // Keep UI text short.
-----
**Show Solution?**

If you just want a hint, click **Cancel** and then **Hint**.

[Cancel] [Show Solution]

**Comment by johnpryan** [comment]
Cool, that's been updated. One small difference is capitalization:

"Show Solution" -> "Show solution"

File: lib/experimental/new_embed.dart [hunk 1]
```diff
@@ -43,6 +43,38 @@ class NewEmbedOptions {
...
+
+Future<DialogResult> showDialog(String title, String htmlMessage,
+    {String yesText = "Yes", String noText = "No"}) {
+  querySelector('#my-dialog-title').text = title;
+  querySelector('#my-dialog-content')
+      .setInnerHtml(htmlMessage, validator: PermissiveNodeValidator());
+
+  var yesButton = querySelector('#dialog-yes')..text = yesText;
+  var noButton = querySelector('#dialog-no')..text = noText;
+  var dialog = MDCDialog(document.querySelector('.mdc-dialog'));
```
Comment (RedBrogdon) [inline lib/experimental/new_embed.dart]: The paradigm we use elsewhere in the file is that long-lived parts of the DOM get a long-lived Dart object to represent them. We have one TabController object that lives forever, for example, since the tab HTML is in the original file, but the HTML that's created on the fly for individual analyzer messages doesn't get that kind of treatment.

If I'm reading this right, `showDialog` would be a departure from that. Would it be better to create a long-lived dialog object that's repeatedly opened and closed, or is this definitely the way to go?

Comment (RedBrogdon) [reply lib/experimental/new_embed.dart]: Also, do we care what happens if the dialog's already open when `showDialog` is called?

Comment (RedBrogdon) [reply lib/experimental/new_embed.dart]: Also: this change helps me, as I need a dialog for #1065. 😄

File: lib/experimental/new_embed.dart [hunk 2]
```diff
@@ -674,12 +700,41 @@ class NewEmbed {
...
+          .listen((_) => selectTab(tab.name, force: _userHasSeenSolution));
+    } catch (e, st) {
+      print('Error from registerTab: $e\n$st');
+    }
+  }
+
   /// This method will throw if the tabName is not the name of a current tab.
   @override
-  void selectTab(String tabName) {
+  Future selectTab(String tabName, {bool force = false}) async {
```
Comment (RedBrogdon) [inline lib/experimental/new_embed.dart]: Do you anticipate anyone calling this with `force`, or would it be cleaner to just check `_userHasSeenSolution` inside `selectTab`?

File: lib/experimental/new_embed.dart (hunk 1 above)
Comment (johnpryan) [reply lib/experimental/new_embed.dart]: I think it's a good point - it's probably better to keep the MDCDialog object stored so that we aren't repeatedly telling the library to create a new component.

The problem is that I imagine this MDCDialog object would be stored on NewEmbed, but this method is currently used by NewEmbedTabController. I don't think it makes sense to store it there...

File: lib/experimental/new_embed.dart (hunk 2 above)
Comment (johnpryan) [reply lib/experimental/new_embed.dart]: good point, let's remove it for now - it's not clear we're going to need it

**Comment by johnpryan** [comment]
@RedBrogdon PTAL

File: lib/experimental/new_embed.dart (hunk 1 above)
Comment (RedBrogdon) [reply lib/experimental/new_embed.dart]: Also a good point, and the ability to pop up a dialog is likely to be a cross-cutting concern for other parts of the UI.

We could make a global method to pop up the dialog, but that's ugly as well. What about injecting a dialog-launching function to NewEmbedTabController as one of its constructor params?

Comment (RedBrogdon) [reply lib/experimental/new_embed.dart]: Discussed offline and agreed on a slightly different approach. @johnpryan is going to make a Dialog class, an instance of which will be owned by NewEmbed and given to any sub-components that need to show a dialog.

**Comment by johnpryan** [comment]
@RedBrogdon PTAL

File: lib/experimental/new_embed.dart [hunk 3]
```diff
@@ -674,12 +670,41 @@ class NewEmbed {
...
+    if (tabName == 'solution' && !_userHasSeenSolution) {
+      var result = await _dialog.show(
+        'Show solution?',
+        'If you just want a hint, click <span style="font-weight:bold">Cancel'
+            '</span> and then <span style="font-weight:bold">Hint</span>.',
+        yesText: "Show solution",
+        noText: "Cancel",
+      );
+      // Go back to the editor tab
+      if (result == DialogResult.no) {
```
Comment (RedBrogdon) [inline lib/experimental/new_embed.dart]: Could you also just do nothing here and leave the currently selected tab selected?

File: lib/experimental/new_embed.dart [hunk 4]
```diff
@@ -1067,6 +1092,51 @@ class ConsoleExpandController extends ConsoleController {
...
+        _noButton = querySelector('#dialog-no'),
+        _title = querySelector('#my-dialog-title'),
+        _content = querySelector('#my-dialog-content');
+
+  Future<DialogResult> show(String title, String htmlMessage,
+      {String yesText = "Yes", String noText = "No"}) {
+    _title.text = title;
+    _content.setInnerHtml(htmlMessage, validator: PermissiveNodeValidator());
+
+    _yesButton..text = yesText;
```
Comment (RedBrogdon) [inline lib/experimental/new_embed.dart]: nit: is there a need for the cascade here or is that just a typo?

File: lib/experimental/new_embed.dart (hunk 3 above)
Comment (johnpryan) [reply lib/experimental/new_embed.dart]: no, at this point the material-components-web library has already selected the tab

File: lib/experimental/new_embed.dart (hunk 4 above)
Comment (johnpryan) [reply lib/experimental/new_embed.dart]: oops, good catch
