### PR TITLE
Fix escape in vim-insert mode

### LINKED ISSUE #2412: Vim mode is no more working on firefox
- Problem
Whenever i escape editing from insert mode to normal mode, that doesn't work properly, 
More specifically, escape key isn't working.
i tested another online pad(ts, rust) & browser(edge). but it seems the problem of dartpad. 
originally, i was very satisfied and enjoyed coding at dartpad with vim.

Browser: Firefox
Version: 106.0.5 (x64)
Operating system: windows10

### PR DESCRIPTION
**Pull request by parlough**
The solution to enable tabbing in and out of the editor introduced in https://github.com/dart-lang/dart-pad/commit/c53fd078b1baa34ef792feb08ac06c8692d20688 caused conflicts with vim-insert mode, so this change simply disables the extra key bindings when in vim-insert mode and reenables them when leaving.

It also deduplicates the `codeMirrorOptions`.

I **recommend** staging this locally making sure you don't get stuck while in Vim mode. I tested a little but am not too familiar with Vim or its key bindings.

Fixes #2412

### CODE REVIEW

**Comment by domesticmouse** [comment]
Dart analyzer is cranky:

```console
Analyzing dart-pad...

   info - lib/embed.dart:19:[8](https://github.com/flutter/codelabs/actions/runs/3476228517/jobs/5811880684#step:9:9) - Unused import: 'editing/codemirror_options.dart'. Try removing the import directive. - unused_import
   info - lib/playground.dart:23:8 - Unused import: 'editing/codemirror_options.dart'. Try removing the import directive. - unused_import
   info - lib/workshops.dart:1[9](https://github.com/flutter/codelabs/actions/runs/3476228517/jobs/5811880684#step:9:10):8 - Unused import: 'editing/codemirror_options.dart'. Try removing the import directive. - unused_import
```

File: lib/editing/editor_codemirror.dart [hunk 1]
```diff
@@ -34,83 +35,8 @@ class CodeMirrorFactory extends EditorFactory {
...
-        'style': 'highlight-selection-matches',
-        'showToken': false,
-        'annotateScrollbar': true,
-      },
-      'hintOptions': {'completeSingle': false},
-      'scrollbarStyle': 'simple',
-      //'lint': true,
-      'theme': 'zenburn', // ambiance, vibrant-ink, monokai, zenburn
-    };
-
```
Comment (johnpryan) [inline lib/editing/editor_codemirror.dart:113]: 👍 Thanks for cleaning this up.

**Review by johnpryan — APPROVED** [review]
Works on my machine 👍

**Comment by parlough** [comment]
Thanks @johnpryan!
