### PR TITLE
fix: expandable console view null safety errors

### LINKED ISSUE #1944: Expandable console view not working on latest master
## What happened?

Expandable console view is not working on the latest master (in embeds).

## Steps to reproduce problem

1. pull latest master (53e526e0ec7a8ace98f7dfcf1f1f8a00035894b8)
2. run `grind serve`
3. Go to http://localhost:8000/embed-flutter.html?id=1a28bdd9203250d3226cc25d512579ec&null_safety=true&run=true or http://localhost:8000/example/embed.html
4. Observe that the console view throws errors when it is tried to be expanded.

### Browser

Browser: Google Chrome

Version: 91.0.4472.114

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```js
Uncaught LateInitializationError: Field '_splitter' has not been initialized.
    at Object.a (embed_html.dart.js:sourcemap:668)
    at Object.j (embed_html.dart.js:sourcemap:675)
    at jq.geS (embed_html.dart.js:sourcemap:13179)
    at jq.iD (embed_html.dart.js:sourcemap:13217)
    at nC.$1 (embed_html.dart.js:sourcemap:13224)
    at t3.$1 (embed_html.dart.js:sourcemap:10300)
    at F1 (embed_html.dart.js:sourcemap:748)
    at HTMLDivElement.<anonymous> (embed_html.dart.js:sourcemap:756)

embed_html.dart.js:sourcemap:1297 Uncaught TypeError: Instance of 'minified:F<minified:B?>': type 'minified:F<minified:B?>' is not a subtype of type 'List<minified:B>'
    at Object.a (embed_html.dart.js:sourcemap:668)
    at Object.yl (embed_html.dart.js:sourcemap:1297)
    at ca.DM [as a] (embed_html.dart.js:sourcemap:1292)
    at jq.iD (embed_html.dart.js:sourcemap:13205)
    at nC.$1 (embed_html.dart.js:sourcemap:13224)
    at t3.$1 (embed_html.dart.js:sourcemap:10300)
    at F1 (embed_html.dart.js:sourcemap:748)
    at HTMLDivElement.<anonymous> (embed_html.dart.js:sourcemap:756)
```

### Machine

Operating system: Win 10

### PR DESCRIPTION
**Pull request by mzdm**
Fixes #1944

### CODE REVIEW

File: lib/elements/tab_expand_controller.dart [hunk 1]
```diff
@@ -37,7 +37,7 @@ class TabExpandController {
   final List<StreamSubscription<Event>> _subscriptions = [];
 
   late TabState _state;
-  late Splitter _splitter;
+  Splitter? _splitter;
```
Comment (johnpryan) [inline lib/elements/tab_expand_controller.dart:40]: This can still be `late` I think

File: lib/elements/tab_expand_controller.dart [hunk 2]
```diff
@@ -209,7 +209,7 @@ class TabExpandController {
       return;
     }
 
-    _splitter.destroy();
+    _splitter?.destroy();
```
Comment (johnpryan) [inline lib/elements/tab_expand_controller.dart:212]: Same here, I don't think `_splitter` needs to be nullable

**Review by johnpryan — CHANGES_REQUESTED** [review]

File: lib/elements/tab_expand_controller.dart (hunk 1 above)
Comment (mzdm) [reply lib/elements/tab_expand_controller.dart]: > This can still be `late` I think

Yes, I just tried and it does not seem to be throwing `LateInitializationError`.

**Review by johnpryan — APPROVED** [review]
Thanks for fixing this!
