### PR TITLE
filter out paths to SDKs in stack traces

### LINKED ISSUE #1035: Cloud storage locations appearing in stacktraces
This code:

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Title!'),
        ),
        body: Row(
          children: [
            SizedBox.expand(
              child: Text('asdfasdf'),
            ),
          ],
        ),
      ),
    );
  }
}
```

Produces an exception in the console that looks like this (actual urls redacted):

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
BoxConstraints forces an infinite width.
The offending constraints were:
  BoxConstraints(w=Infinity, h=283.0)
When the exception was thrown, this was the stack:
Error: BoxConstraints forces an infinite width.
The offending constraints were:
  BoxConstraints(w=Infinity, h=283.0)
    at Object.dart.throw
    (https://enormous.cloud.url.string:4537:11)
    at src__rendering__box.BoxConstraints.new.<anonymous>
    (https://enormous.cloud.url.string::96550:21)
    at
    https://enormous.cloud.url.string::96579:43
    ..etc...
```

We should figure out how to eliminate or filter out these messages.

### PR DESCRIPTION
**Pull request by johnpryan**
closes #1035

### CODE REVIEW

File: lib/experimental/filter_output.dart [hunk 1]
```diff
@@ -0,0 +1,11 @@
+final RegExp _flutterUrlExp =
```
Comment (RedBrogdon) [inline lib/experimental/filter_output.dart]: If these are going to be in a separate file, you'll need to pop the copyright header in at the top.

File: test/experimental/filter_output_test.dart [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+import 'package:dart_pad/experimental/filter_output.dart';
+
+void main() {
+  group('filterCloudUrls', () {
+    test('cleans dart SDK urls', () {
+      var trace =
+          '(https://storage.googleapis.com/compilation_artifacts/2.2.0/dart_sdk.js:4537:11)';
+      expect(filterCloudUrls(trace), '([Dart SDK Source]:4537:11)');
+    });
+    test('cleans dart SDK urls', () {
```
Comment (RedBrogdon) [inline test/experimental/filter_output_test.dart]: Flutter SDK Urls?

File: lib/experimental/filter_output.dart (hunk 1 above)
Comment (johnpryan) [reply lib/experimental/filter_output.dart]: Good point. Moved this code into the existing file instead
